var subject = require('./subject.js')
var mock = require('mock-fs');
var faker = require('faker');subject.inc('',undefined);
subject.inc('','');
subject.inc(0,'');
subject.inc(-1,'');
subject.inc(-1,'');
subject.fileTest('path/fileExists','');
subject.fileTest('path/fileExists','path/fileExists');
subject.fileTest('path/fileExists','pathContent/file1');
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"fileNo":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"fileNo":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
subject.fileTest('path/fileExists','pathContent/file1');
subject.normalize('(834) 020-4750');
subject.format('0010011010','(NNN) NNN-NNNN)',{"normalize": true});
subject.format('0010011010','(NNN) NNN-NNNN)','');
subject.format('(244) 608-2485','492-029-2757','');
subject.blackListNumber('165-118-2293 x25479');
subject.blackListNumber('2120000000');
