var subject = require('./subject.js')
var mock = require('mock-fs');
var faker = require('faker');subject.inc('',undefined);
subject.inc('','');
subject.inc(0,'');
subject.inc(-1,'');
subject.inc(-1,'');
subject.fileTest('path/fileExists','');
subject.fileTest('path/fileExists','path/fileExists');
subject.fileTest('path/fileExists','pathContent/file1');
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"fileNo":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"fileNo":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
subject.fileTest('path/fileExists','pathContent/file1');
subject.normalize('(849) 897-9811 x085');
subject.format('0010011010','(NNN) NNN-NNNN)',{"normalize": true});
subject.format('0010011010','(NNN) NNN-NNNN)','');
subject.format('081.723.0804 x468','197-234-1312','');
subject.blackListNumber('653.909.4524 x181');
subject.blackListNumber('2120000000');
